### PR TITLE
Update breakpt-ex.Rmd

### PR DESCRIPTION
**Pull request by dquigley533**
Just tweaked a couple of things here after trying them out in the final session.

1. The `opts_slurmR$set_preamble` command didn't seem to be working as expected and R was only available inside the slurmR launched jobs by virtue of module loads in .bashrc. I've added a note on that. If I tried to load the modules just with the set_preamble command then I got library errors.

2. Updated the module load command for ZeroMQ so that it would match the toolchain used for R.

Your mileage may vary of course.

### CODE REVIEW

**Comment by mschubert** [comment]
Hi David,

Thank you!

I'm a bit reluctant to put the PDF in, because it will stay in the repository history and make it quite a bit larger.
Could we put  this in a "release" instead?

**Comment by dquigley533** [comment]
Sorry - I didn't actually mean for the pdf to be part of the pull request. Just the updated to breakpt-ex.Rmd. My GitHub skills are not where they should be.

I was just wanting to the pdf to be in my fork so we've got the canonical version we delivered for the funder's reference.

**Comment by mschubert** [comment]
Ok, I'll edit it & let you add the PDF in your fork afterwards

**Comment by mschubert** [comment]
Merged manually without the pdf

**Comment by mschubert** [comment]
@dquigley-warwick I think if you pull from this repository to @sulis-hpc you're all set.

When you're done, I'll push my master without the 2 most recent commits

**Pull request closed without merging**
